Re-introduce RequireLinkAvailability feature to v3
thinktecture/relayserver pull request #385
Opened 2022-10-25 11:52 UTC by gingters

2022-12-22 11:14 UTC, thomashilzendegen requested changes

2022-12-22 11:14 UTC, thomashilzendegen commented on docs/configuration.md
> +### RequireActiveConnection
```suggestion
### Require active connection
```

2022-12-22 11:14 UTC, thomashilzendegen commented on docs/configuration.md
> +request can immediately be rejected with a 503 - Service unavailable status code.
```suggestion
request will be immediately rejected with a 503 - Service unavailable status code.
```

2022-12-22 11:14 UTC, thomashilzendegen commented on src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
> +	private readonly struct TenantInfo
Sometimes this is called `TenantInformation` and sometimes `TenantInfo`. This needs to be harmonized.

2022-12-22 13:42 UTC, thomashilzendegen commented on src/Thinktecture.Relay.Server/Middleware/RelayMiddleware.cs
> +	[LoggerMessage(20615, LogLevel.Debug, "Request to tenant {Tenant} was rejected due to no active connection")]
The event id is already used in line `302`

2023-01-17 09:29 UTC, gingters commented
Rebased and updated with requested changes.

2023-01-17 16:03 UTC, thomashilzendegen approved these changes

2023-01-17 16:03 UTC, merged